version: '3.8'
services:
  users-api:
    build:
      context: .
      target: develop
    command: >
      sh -c 'flake8 -v --show-source app ; 
        python app/manage.py migrate &&
        python app/manage.py runserver 0.0.0.0:7001'
    restart: always
    ports:
    - 7001:7001
    volumes:
    - ./src:/srv/app
    - ./Pipfile:/srv/Pipfile
    - ./Pipfile.lock:/srv/Pipfile.lock
    environment:
      SECRET_KEY: 'y-mxg_e8!jvef4t#mg*_7h(&3y$czfa9^dh$2q2#6pth-2(+-3'
      DEBUG: True
      DB_NAME: users
      DB_USERNAME: user
      DB_PASSWORD: P@ssw0rd
      DB_HOSTNAME: postgres
    depends_on:
    - postgres
  postgres:
    image: postgres:15.3-alpine3.18
    restart: always
    environment:
      POSTGRES_DB: users
      POSTGRES_USER: user
      POSTGRES_PASSWORD: P@ssw0rd
    volumes:
    - ./pgdata:/var/lib/postgresql/data
    ports:
      - 5432:5432
